import mysql.connector
from mysql.connector import errorcode
print("ok")
try:
 cnx = mysql.connector.connect(user='root', password='HARDWARE',
                               host='127.0.0.1',
                               database='weather_data')

 cur = cnx.cursor()

 query = "SELECT * FROM loaddata"
 rows = cur.execute(query)
 for row in rows :
   print row

 cnx.commit()

except mysql.connector.Error as err:
  if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
    print("Something is wrong with your user name or password")
  elif err.errno == errorcode.ER_BAD_DB_ERROR:
    print("Database does not exist")
  else:
    print(err)
else:
  cnx.close()
